'use strict';
const faker = require("faker");

drinks = [ //250 beers from thebeerguy.ca/alphabetical-list-of-beer
`4 Degrees Brewing Hill 70 Belgian Blonde Ale	5 Oclock Shadow Pale Ale`, 
`5 Paddles Brewing Home Sweet Home	5 Paddles Brewing In Your Face Ipa`, 
`5 Paddles Home Sweet Home	8 .6 Extreme`, 
`Abbot Ale	Abe Erb 1857 Kolsch-Style Ale`, 
`Abe Erb Das Spritzhaus Hefeweizen	Ace Hill Dry Hopped Lager`, 
`Ace Hill Lime Radler	Ace Hill Mexican Lager`, 
`Ace Hill Pilsner	Ace Hill Radler`, 
`Ace Hill Radler Mix Pack	Ace Hill Vienna Lager`, 
`Ace Hill Winter Radler	Aecht Schlenkerla Rauchbier`, 
`Akatsuki Sake	Alberta Genuine Draft`, 
`Alexander Keiths Red	All or Nothing Brewhouse Pushin the Limits India Pale Lager`, 
`All Or Nothing Hustle Over Hype Pale Wheat	All Or Nothing Hustle Over Hype Pale Wheat Ale`, 
`All or Nothing Mead Braggot	All or Nothing snooze you loose honey brown`, 
`All or Nothing Think Big'Ger Cream Ale	All Or Nothing Think Bigger Cream Ale`, 
`Alpine Lager	Amager Rye King Danish Stout`, 
`Amber Taybeh Beer	American Vintage Iced Tea Lemon Malt`, 
`Amsterdam 3speed Lager	Amsterdam Big Wheel`, 
`Amsterdam Boneshaker	Amsterdam Boneshaker Gift Set`, 
`Amsterdam Cruiser All Day Pale Ale	Amsterdam Downtown Brown`, 
`Amsterdam Fracture Imperial Ipa	Amsterdam Fria Cervesa`, 
`Amsterdam Hazy Town IPA	Amsterdam Makes You Pucker`, 
`Amsterdam Natural Blonde	Amsterdam Pale Rider`, 
`Amsterdam Space Invader Ipa	Amsterdam Summer Flight Pack`, 
`Amsterdam Winter Flight Pack	Anderson Ale's Summer Pilsner`, 
`Anderson Amber Ale	Anderson Craft Ale Winter Dubbel`, 
`Anderson Craft Ales - Autumn	Anderson Cream Ale`, 
`Anderson Gold Lager	Anderson Ipa`, 
`Anderson Juicier IPA	Anderson Juicy IPA`, 
`Angry Orchard Hard Cider Crisp Apple	Aquarelle Mango`, 
`Ardiel Cider House Dry Cider	Ardiel Cider House Victoria Pear Cider`, 
`Aria Ipa	Aria Lager`, 
`Aria Porter	Asahi Super Dry`, 
`Ashton Brewing Amber Ale	Ashton Brewing Blueberry Wheat`, 
`Ashton Brewing Brown Ale	Ashton Brewing Company Blueberry Wheat`, 
`Ashton Brewing Company Cream Ale	Aventinus Eisbock`, 
`Awayuki Sparkling Sake	Backpaddle Bonde Ale`, 
`Badger Fursty Ferret	Ballast Point Grapefruit Sculpin IPA`, 
`Baltika 7	Bancroft Brewing Rusty Husky`, 
`Bancroft Brewing Sawmill Lager	Bard's Gold`, 
`Barley Days Harvest Gold	Barley Days Loyalist Lager`, 
`Bavaria 0.0% Original Beer	Bavaria 8.6`, 
`Bavaria 8.6 Red	Bavaria Premium`, 
`Bavaria Premium Beer	Bavarian Alps Collector Bottle Gift Pack`, 
`Bayside Brewing Bronzeback Dark Ale	Bayside Brewing Honey Cream Ale`, 
`Bayside Brewing Long Pond Lager	Bayside Brewing Orchard Cherry Lager`, 
`Beach Chair Lager	Beach Day Every Day Berry Beach`, 
`Beach Day Every Day Fruit Punch	Beaches Brewing Co. A-Bay Pale Ale`, 
`Bear Runner Blonde Ale	Bearded Prospector Cream Ale`, 
`Beau's Countdown Pale Ale	Beau's Country Vibes Amber Lagered Ale`, 
`Beau's Davids Tea London Fog	Beau's Full Time IPA`, 
`Beau's Good Time Session IPA	Beau's Halcyon Barrel House Curse of Knowledge`, 
`Beau's Halcyon Barrel House Echo Chamber	Beau's Holiday Giftpack 2020`, 
`Beau's Lug Tread 2.5%	Beau's Lug Tread Lagered Ale`, 
`Beau's Mix Pack	Beau's Night Marzen`, 
`Beau's Radler	Beau's Strong Patrick`, 
`Beau's Wag the wolf white IPA	Beaus Fall Winter Mix Pack`, 
`Beaus Wag The Wolf White Ipa	Becks`, 
`Becks Non Alcoholic 0.0	Beer Devil Ipa`, 
`Beer League Lager	Bek Se Ju`, 
`Belgian Beer Discovery Box	Belgian Moon`, 
`Belgian Moon Light Sky	Belhaven Black Scot Stout`, 
`Belhaven Brewery Merry Craftmas	Bell City Brewing Too Wound Down Session IPA`, 
`Bell City Edison's Peep Show IPA	Bell City Elijahs Real McCoy Lager`, 
`Bell City Too Wound Down New England Session Ipa	Belle Gueule`, 
`Bellwoods Brewery Jelly King	Bellwoods Brewery Jutsu Pale Ale`, 
`Bellwoods Brewery Roman Candle	Bellwoods Brewery, Fruit Jelly King Raspberry & Blackberries`, 
`Bench Ball's Falls Session Ipa	Bench Brewing Ball's Falls Session IPA`, 
`Bench Brewing Cherry Grove Sour	Bench Brewing Folklore Dark Sour Ale`, 
`Bench Brewing Green Fields Sour	Bench Brewing Jordan Harbour Belgian Pale Ale`, 
`Bench Brewing Lincoln Lager	Bench Brewing Oak Grove Sour Ale`, 
`Bench Brewing Pinot Noir Wildwood Barrel Aged Sour	Bench Brewing Short Hills East Coast IPA`, 
`Bench Brewing Stone Road White Ale	Bench Jordan Harbour Belgian Pale Ale`, 
`Benediktiner Hell	Berliner Pilsner`, 
`Berry White Raspberry Wheat	Beswick Lager`, 
`Beyond The Pale Aromatherapy	Beyond The Pale Aromatherapy IPA`, 
`Beyond The Pale Brewing Co. Yummy!	Beyond The Pale Clean Cut`, 
`Beyond The Pale Pale Ale Project	Beyond The Pale Pink Fuzz`, 
`Bicycle Craft Brewery Frequency APA	Bicycle Craft Velocipede IPA`, 
`Big Drop Brewery Co Pale Ale	Big Drop Brewery Stout`, 
`Big Rig Alpha Bomb Ipa	Big Rig Black Ipa Release The Hounds`, 
`Big Rig Brewery Shakedown APA	Big Rig Canadian Amber`, 
`Big Rig Gold	Big Rig Hazy Session IPA`, 
`Big Rig Midnight Kissed My Cow	Big Rig Premium`, 
`Big Rig Premium Pilsner	Big Rig Pumpkin Porter`, 
`Big Rig Shakedown Apa	Big Rock AGD Lager`, 
`Big Rock Bow Valley Lager	Big Rock Citradelic Ipa`, 
`Big Rock Grasshopper Kristallweizen	Big Rock Pilsner`, 
`Big Rock Summer Variety Pack	Big Rock The Darcys Poolside Grapefruit Lager`, 
`Big Rock Traditional Ale	Big Rock Winter Holiday Spice Beer`, 
`Bighead Amber - 100% Ontario Organic Hops	Billy Bishop Double IPA`, 
`Birra Castello	Birra Dell' Eremo Aria Session IPA`, 
`Birra Dell'Eremo Fuoco Tripel Beer	Birra Dell'Eremo Saggia Blanche Wheat Beer`, 
`Birra Moretti	Bitburger`, 
`Black Bellows White	Black Ice`, 
`Black Label	Black Oak 10 Bitter Years`, 
`Black Oak 10 Bitter Years Imperial Ipa	Black Oak Beat the Heat Belgian Wheat`, 
`Black Oak Nut Brown Ale	Black Oak Pale Ale`, 
`Blacklist Black German Lager	Blanche De Chambly`, 
`Blanche Des Honnelles	Blindman Brewing Longshadows IPA`, 
`Block Three Brewing Hollinger Helles	Block Three Brewing King Street Saison`, 
`Blue	Blue Ice`, 
`Blue Light	Bobcaygeon Backyard All Ontario Lager`, 
`Bobcaygeon Brewing Common Loon APA	Bobcaygeon Brewing Dockside`, 
`Bobcaygeon Brewing Foliage Autumn Ale	Bobcaygeon Brewing Holiday Tacklebox`, 
`Bobcaygeon Brewing Northern Lights	Bobcaygeon Brewing Starry Night Chocolate Stout`, 
`Bobcaygeon Common Loon	Bobcaygeon Dockside Ale`, 
`Bobcaygeon Firefly Belgian White	Boddingtons`, 
`Boddingtons Pub Ale	Bohemian`, 
`Bombardier Ale	Bombshell Blonde Ale`, 
`Boreale Pale Ale Des Bois	BORN Dreams Come True Junmai Ultra Dai`, 
`Boshkung 35 & 118 Cream Ale	Boshkung Brewing North Country Kellerbier`, 
`Boshkung Campfire Rye Ale	Boss Black - Blackcurrant Edition`, 
`Boss Brewing Company Black Stout	Boulevard Brewing Co Rye On Rye 6 Ale`, 
`Boxer Ice	Boxer Lager Gluten Free`, 
`Brasserie De Blaugies La Moneuse Saison	Brasserie Dubuisson Scaldis Ambree`, 
`Brasserie Tuque De Broue Gougounes Rousses	Brasserie Tuque De Broue Tuque Doree`, 
`Brava	Brava 5.5`, 
`Brava Light	Brew Microbrewery Maple Beer`, 
`Brew Revolution Neipa - Walkin On Sunshine	Brewdog Brewing Lost Lager`, 
`Brewdog Punk IPA	Brewski Halo`, 
`Brickworks Cherry Cider	Brickworks Ciderhouse Batch: 1904`, 
`Brickworks Ciderhouse Burgundy Effect	Brickworks Ciderhouse Cider Spritz`, 
`Brickworks Ciderhouse Lemonade Cider Radler	Brickworks Ciderhouse Mint & Basil`, 
`Brickworks Ciderhouse Mixed Pack	Brickworks Ciderhouse Queen Street 501`, 
`Brickworks Ciderhouse Rose Cider	Brickworks Ciderhouse Stadium Island Peach Cider`, 
`Brimstone Brewing Last Ride Loganberry	Brimstone Brewing Sinister Minister IPA`, 
`Brimstone Punk Rock Pilsner	Broad Reach Nor-Easter Ipa`, 
`Broadhead Amber Ale	Broadhead Blueberry Blonde`, 
`Broadhead Lager	Broadhead Neipa`, 
`Broadhead Oatmeal Stout	Broadhead Tangerine Ipa`, 
`Brock Street Blonde	Brock Street Bohemian Pilsner`, 
`Brock Street Brewing Munich Lager	Brock Street Brewing New England Session IPA`, 
`Brock Street Brewing Strong Scotch Ale	Brock Street Strawberry Blonde`, 
`Brock Street Traditional Irish Red	Brooklyn Lager`, 
`Brouczech Premium Lager	BROUWERIJ De Moersleutel Dolle Dries 2 Imperial Porter`, 
`Bruce Trail Blonde Ale	Brugse Zot Blond`, 
`Bud Light	Bud Light Apple`, 
`Bud Light Chelada	Bud Light Lemonade Radler`, 
`Bud Light Lime	Bud Light Orange`, 
`Bud Light Radler	Bud Light Strawberry Lemonade`, 
`Bud Light Summer Mixer	Budweiser`, 
`Budweiser Nitro Gold	Budweiser Prohibition`, 
`Budweiser Shot	Budweiser Zero`, 
`Bulwark Cider Blush	Burdock Brewery Tuesday Saison`, 
`Busch	Busch Ice`, 
`Busch Ice 6.0	Busch Light`, 
`Buzz Hemp Beer	Calabogie Brewing Bogie`, 
`CALABOGIE BREWING Brown Cow Milk Stout	Calabogie Brewing K & P Ale`, 
`Calabogie Front Porch Kolsch	Calabogie Portage Pilsner`, 
`Calabogies Bogie West Coast American Ipa	Calabogies Brown Cow Nitro Stout`, 
`Caledon Hills Bohemian Pils	Caledon Hills Deadly Dark`, 
`Caledon Hills Deadly Dark Lager	Caledon Hills Vienna Lager`, 
`Cameron's 12 Mile Lager	Cameron's Ambear Red Ale`, 
`Cameron's Captain's Log Lager	Cameron's Cosmic Cream Ale`, 
`Cameron's Cruising through the Galaxy NEIPA	Cameron's Jurassic IPA`, 
`Cameron's Winter Sampler Pack	Camerons Ambear Red Ale`, 
`Camerons Captains Log	Camerons Cosmic Cream Ale`, 
`Camerons Jurassic Ipa	Canadian`, 
`Canadian Coldshots	Canadian Heritage Gold Pilsner`, 
`Canuck Pale Ale	Carib Lager`, 
`Caribru Ipa	Caribru Lager`, 
`Carling Ice	Carling Lager`, 
`Carling Light	Carlsberg`, 
`Carlsberg Lite	Cascade Brewing Midnight Bramble`, 
`Cascade Brewing Rose City Sour	Cascade Brewing Sang Royal`, 
`Cascade Brewing Vitis Noble	Cassel Brewery Caboose IPA`, 
`Cassel Brewery Franco Lager Artisanale	Catapult Brewing American Pale Ale`, 
`CATAPULT BREWING Kolsch Style Lagered Ale	Cherry River Yuzu Lime`, 
`Cheval Blanc	Chimay Blue Cap`, 
`Chimay Gold	Chimay Premiere`, 
`Chimay White Cap	Chocolate Nigori`, 
`Chokarakuchi Junmai	Choya Yuzu`, 
`Chug Life	Church Key Holy Smoke Scotch Ale`, 
`Church Key Northumberland Ale	Cigar City Florida Cracker Belgian Style Wit`, 
`Cigar City Florida Man Double IPA	Cigar City White Oak Jai Alai Ipa`, 
`Class V Ipa	Clausthaler Premium Non Alcoholic`, 
`Clear Lake Session Ale	Cliff Top Pale Ale`, 
`Clifford Brewing Chain Link Lager	Clifford Brewing Devils Punchbowl India Session Lager`, 
`Clifford Brewing Porter	Clutch American Pale Ale`, 
`Coffin Ridge Forbidden Artisanal Cider	Collective Arts Audio Visual Lager`, 
`Collective Arts Blueberry Chocolate & Coffee Sour	Collective Arts Circling The Sun Applecherry Cider`, 
`Collective Arts Hazy State	Collective Arts Imperial Bourbon Barrel Aged Porter Gift`, 
`Collective Arts IPA # 14	Collective Arts IPA No 15`, 
`Collective Arts Jam Up The Mash	Collective Arts Life In The Clouds`, 
`Collective Arts Nature Of Things Dry Cider	Collective Arts Pomegranate & Grapefruit Sour`, 
`Collective Arts Radio The Mothership IIPA	Collective Arts Ransack The Universe IPA`, 
`Collective Arts Raspberry Dry Hopped Sour	Collective Arts Rhyme & Reason`, 
`Collective Arts Saint Of Circumstance	Collective Arts Stranger Than Fiction, Porter`, 
`Collective Arts Surround Sound	Collingwood Brewery Freestyle Vanilla Oatmeal Stout`, 
`Collingwood Brewery Rockwell Pilsner	Collingwood Brewery Strawberry Milkshake IPA`, 
`Collingwood Downhill Pale Ale	Collingwood Hazy Session Ale`, 
`Collingwood Rockwell Pilsner	Collingwood Stout`, 
`Collingwood Whites Bay IPA	Colt 45`, 
`Cool Beer Blonde Lager	Cool Beer Lager`, 
`Coors Edge 0.5	Coors Light`, 
`Coors Light Minis	Coors Organic`, 
`Coors Original	Coors Slice Lime`, 
`Coors Slice Orange	Coors Summer Mix`, 
`Corona	Corona Import`, 
`Corona Light	Coronita Extra`, 
`County Apple Cider	County Pear Cider`, 
`Covered Bridge Brewing Lumbersexual Session IPA	Covered Bridge Walk on the Mild Side`, 
`Cowbell Absent Landlord	Cowbell Brewing Co. Absent Landlord`, 
`Cowbell Brewing Co. Brewing Co McNall's Mission	Cowbell Brewing Co. Doc Perdue's Bobcat`, 
`Cowbell Brewing Co. Doc Perdue's Boxing Bruin	Cowbell Brewing Co. Double Exposure Double IPA`, 
`Cowbell Brewing Co. Gravel Run Session IPA	Cowbell Brewing Co. Hazy Days IPA`, 
`Cowbell Brewing Co. Sea Salt Grapefruit Sour	Cowbell Brewing Co. Shindig Huron County Lager`, 
`Cowbell Brewing Co. Winter Collection	Cowbell Brewing Raspberry Moon Fruit Sour IPA`, 
`Cowbell Doc Perdues Bobcat	Crank Lite Lager`, 
`Creemore Boundless Ipa	Creemore Collection Pack Featuring IPA`, 
`Creemore Collection with Urbock	Creemore Lot 9 Pilsner`, 
`Creemore Mad & Noisy	Creemore Premium Lager`, 
`Creemore Springs Collection	Creemore Springs Helles Lager`, 
`Creemore Springs Holiday Gift Pack	Creemore Springs Urbock`, 
`Creemore Summer Collection	Creemore Winter Collection`, 
`Crest Super	Cruiser All Day Pale Ale`, 
`Crystal	Cup & Saucer English Ale`, 
`Czechvar	Czechvar Mini Keg`, 
`D'Ont Poke The Bear Berry Cider	D'ont Poke The Bear Cider`, 
`Dab Dark Lager	Dab Lemon Radler Unfiltered`, 
`Dab Maibock	Dab Original Lager`, 
`Dab Ultimate Low Carb Beer	Dai-Ginjo Jyuhachidai Ihei Sake`, 
`Danforth Brewery Viaduct IPA	Daura Damm`, 
`De Liete Mam Zelle	De Moersleutel Rusty Brown Ale`, 
`Deadline Premium Blonde Lager	Death Valley Triple Hop Ale`, 
`DeLeite Cuvee Jeun'homme Belgian Oak Age Sour	Delirium Tremens`, 
`Deschutes Black Butte Porter	Deschutes Da Shootz! American Pilsner`, 
`Designated Draft 0.5	Dewazakura Aiyama Junmai Daiginjo Sake`, 
`Dewazakura Dewanosato Junmai Saké	Dewazakura Dewanosato Junmai Sake`, 
`Dewazakura Ginjo Can	Dewazakura Oka Ginjo`, 
`Dewazakura Oka Ginjo Sake	Dewazakura Tobiroku Sparkling Ginjo Sake`, 
`Dewazakura Tsuyahime Junmai Ginjo	Dirndl 2 Bottle Gift Pack`, 
`Divercity Helles Lager	Dominion City Town & Country Blonde Ale`, 
`Dominion City Two Flags Ipa	Doppel Hirsch Doppel Bock`, 
`Dos Equis Amber	Dos Equis Lager`, 
`Double Drooling Dog Black Ipa	Double Trouble Hops & Robbers Grapefruit IPA`, 
`Double Trouble Hops & Robbers IPA	Double Trouble Pecan Porter`, 
`Dragon Stout	Dragon's Gold Cider`, 
`Driftwood Brewing Fat Tug IPA	Duchesse De Bourgogne`, 
`Duggans #9 IPA	Duggans Sorachi Lager`, 
`Dunes Beach Beer	Duntroon Cyder House - Raindance Rhubarb Infused`, 
`Duntroon Cyder House Standing Rock	Duvel Beer`, 
`Duvel Tripel Hop Cashmere	Duxbury Cider Co Original Sideroad Dry Cider`, 
`Eagle Banana Bread Beer	Eagle IPA`, 
`East Hamilton Lager German Style Pilsner	East Street Cider Co. Landmark Dry Cider`, 
`Eastbound Brewing Co Backpacker Blonde Ale	Ebb & Flow Plum and Boysenberry`, 
`Eden Grove Hibiscus Blossom Cider	Eden Grove Perfect Pear`, 
`Eden's Apple Strawberry Craft Cider	Edinburgh Beer Factory - Paolozzi Unfiltered Craft Lager`, 
`Einbecker Ur-Bock Hell	Einstok Icelandic Arctic Berry Ale`, 
`El Camino Cerveza	Elora Brewing Borealis Pale Ale`
] 

const profiles = [
  `Clean/Delicate Fruit`, 
  `Malt-Accented`, 
  `Brisk Hop`,
  `Earthy & Dry`, 
  `Malt Forward`, 
  `Bold/Strong Hop`, 
  `Herbal & Citrus`,
  `Toasty & Nutty`, 
  `Fruit & Toffee/Caramel`,
  `Soft & Silky/Malty`, 
  `Dark & Dry`,
  `Subdued Smolder`,
  `Spicy & Meaty`,
  `Bright & Yeasty`, 
  `Dark`,
  `Delicate`, 
  `Fruity & Vinous`, 
  `Earthy`
]



const beer =  drinks[(Math.floor(Math.random() * 250))]
const description =  `This ${faker.hacker.adjective()} beer has a ${profiles[(Math.floor(Math.random() * 17))]} flavor profile`

const fakeItems = (num) => {
  const fakeItemsArray = []
  while (num > 0){
    fakeItemsArray.push({name:beer, description:description})
    num -= 1
  }
  return fakeItemsArray
}

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Items', [...fakeItems(2700)], {});
  },
  
  down: (queryInterface, Sequelize) => {
return queryInterface.bulkDelete('Items', null, {});
  
  }
};
